Repository tangorishi/learnJava, pull requests merged in 2023-10, with the labels that each got.

#15 Create FizzBuzz.java
  16_FirstContribution/FizzBuzz.java
Labels: Hacktoberfest-accepted

#41 Add Java code examples for Sorting Algorithm
  16_FirstContribution/SORTING/BubbleSort.java
  16_FirstContribution/SORTING/MergeSort.java
  16_FirstContribution/SORTING/SelectionSort.java
Labels: Hacktoberfest-accepted

#45 Create CustomLinkedList.java
  16_FirstContribution/CustomLinkedList.java
Labels: Hacktoberfest-accepted

#53 Add Java code examples for Buzz Number Checker in Java
  16_FirstContribution/BuzzNumberChecker.java
Labels: Hacktoberfest-accepted

#52 Add java code for Number to Word converter
  16_FirstContribution/NumberToWordsConverter.java
Labels: Hacktoberfest-accepted

#44 Neon Numbers Generator
  16_FirstContribution/NeonNumbers.java
Labels: Hacktoberfest-accepted

#47 Update polymorphism.md
  11_Polymorphism/polymorphism.md
Labels: Hacktoberfest-accepted

#57 Update file_io.md
  13_File_io/file_io.md
Labels: enhancement, Hacktoberfest-accepted

#58 Update gui_programming.md
  14_GUI_programming/gui_programming.md
Labels: enhancement, Hacktoberfest-accepted

#59 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#25 Add java code examples for PasswordGenerator
  16_FirstContribution/PasswordGenerator.java
Labels: Hacktoberfest-accepted

#56 Add Java code for Fibonacci Sequence Generator
  16_FirstContribution/FibonacciSequenceGenerator.java
Labels: Hacktoberfest-accepted

#55 Dijkstra's Algorithm uploaded
  16_FirstContribution/Dijkstra's algorithm/Dijkstra.java
  16_FirstContribution/Dijkstra's algorithm/DijkstraTest.java
  16_FirstContribution/Dijkstra's algorithm/Exxplanation.md
Labels: Hacktoberfest-accepted

#71 Create Floyd-Warshall-Algorithm.java
  16_FirstContribution/Algorithms/Floyd-Warshall-Algorithm.java
Labels: Hacktoberfest-accepted

#76 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#68 Add some number identifying programs
  16_FirstContribution/Numbers/ArmstrongNumber.java
  16_FirstContribution/Numbers/AutomorphicNumber.java
  16_FirstContribution/Numbers/HappyNumber.java
  16_FirstContribution/Numbers/KaprekarNumber.java
  16_FirstContribution/Numbers/KrishnamurthyNumber.java
  16_FirstContribution/Numbers/PalindromeNumber.java
  16_FirstContribution/Numbers/PerfectNumber.java
  16_FirstContribution/Numbers/PrimeNumber.java
  16_FirstContribution/Numbers/PronicNumber.java
  16_FirstContribution/Numbers/UniqueNumber.java
Labels: Hacktoberfest-accepted

#78 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#79 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#48 Code for findng the small and largest of 10 values
  16_FirstContribution/minMax.java
Labels: Hacktoberfest-accepted

#60 super washing machines code added
  16_FirstContribution/SuperWashingMachines.java
Labels: Hacktoberfest-accepted

#92 Update README.md
  README.md
Labels: Hacktoberfest-accepted

#83 Create TriangularNumber.java
  16_FirstContribution/Numbers/TriangularNumber
Labels: Hacktoberfest-accepted

#103 Create 2D_Arrays
  06_Arrays/2D_Arrays
Labels: Hacktoberfest-accepted

#101 Snake & ladder Game
  16_FirstContribution/Algorithms/FloydWarshall.java
  16_FirstContribution/FizzBuzz.java
  16_FirstContribution/Games/SnakeLadder/Game.java
  16_FirstContribution/Games/SnakeLadder/Ladder.java
  16_FirstContribution/Games/SnakeLadder/Player.java
  16_FirstContribution/Games/SnakeLadder/Snake.java
  16_FirstContribution/PlaySnakeNLadder.java
  16_FirstContribution/WashingMachine.java
Labels: enhancement, Hacktoberfest-accepted

#97 Feature/stream api
  16_FirstContribution/Patterns/ButterflyPattern.java
  17_Stream_API/stream_api.md
Labels: Hacktoberfest-accepted

#111 Create InsertionSort
  16_FirstContribution/SORTING/InsertionSort
Labels: duplicate, Hacktoberfest-accepted

#115 Create StonePaperScissors
  16_FirstContribution/StonePaperScissors
Labels: enhancement, Hacktoberfest-accepted

#110 Add some GUI Program examples
  16_FirstContribution/GUI Programs/DigitalClock.java
  16_FirstContribution/GUI Programs/SwingCalculator.java
  16_FirstContribution/GUI Programs/TemperatureConverter.java
Labels: Hacktoberfest-accepted

#108 Add documentation for multithreading in Java
  18_Multithreading/multithreading.md
  README.md
Labels: enhancement, Hacktoberfest-accepted
